// Protobuf-Form des Live-Change-Streams (`SPEC-020`, `ADR-0060`
// Teilfrage 1): ein Server-Streaming-RPC, der je verbundenem Consumer
// jeden einzelnen committed Change mit vollständigem Inhalt überträgt
// (`LH-FA-SST-008`) — fire-and-forget ohne Replay (`ADR-0060`
// Teilfrage 3).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: cdc/stream/v1/changestream.proto

package streamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChangeStream_StreamChanges_FullMethodName = "/cdc.stream.v1.ChangeStream/StreamChanges"
)

// ChangeStreamClient is the client API for ChangeStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChangeStream trägt die eine Streaming-Fähigkeit dieses Adapters
// (`SPEC-020`).
type ChangeStreamClient interface {
	// StreamChanges öffnet den Server-Stream und überträgt jeden ab
	// Verbindungsaufbau eintreffenden Change; ein Öffnungsversuch ohne
	// gültige Authentifizierung endet mit gRPC-Status `Unauthenticated`
	// (`LH-FA-SST-008` Negative, `ADR-0060` Teilfrage 4).
	StreamChanges(ctx context.Context, in *StreamChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Change], error)
}

type changeStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeStreamClient(cc grpc.ClientConnInterface) ChangeStreamClient {
	return &changeStreamClient{cc}
}

func (c *changeStreamClient) StreamChanges(ctx context.Context, in *StreamChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Change], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChangeStream_ServiceDesc.Streams[0], ChangeStream_StreamChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChangesRequest, Change]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeStream_StreamChangesClient = grpc.ServerStreamingClient[Change]

// ChangeStreamServer is the server API for ChangeStream service.
// All implementations must embed UnimplementedChangeStreamServer
// for forward compatibility.
//
// ChangeStream trägt die eine Streaming-Fähigkeit dieses Adapters
// (`SPEC-020`).
type ChangeStreamServer interface {
	// StreamChanges öffnet den Server-Stream und überträgt jeden ab
	// Verbindungsaufbau eintreffenden Change; ein Öffnungsversuch ohne
	// gültige Authentifizierung endet mit gRPC-Status `Unauthenticated`
	// (`LH-FA-SST-008` Negative, `ADR-0060` Teilfrage 4).
	StreamChanges(*StreamChangesRequest, grpc.ServerStreamingServer[Change]) error
	mustEmbedUnimplementedChangeStreamServer()
}

// UnimplementedChangeStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChangeStreamServer struct{}

func (UnimplementedChangeStreamServer) StreamChanges(*StreamChangesRequest, grpc.ServerStreamingServer[Change]) error {
	return status.Error(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedChangeStreamServer) mustEmbedUnimplementedChangeStreamServer() {}
func (UnimplementedChangeStreamServer) testEmbeddedByValue()                      {}

// UnsafeChangeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeStreamServer will
// result in compilation errors.
type UnsafeChangeStreamServer interface {
	mustEmbedUnimplementedChangeStreamServer()
}

func RegisterChangeStreamServer(s grpc.ServiceRegistrar, srv ChangeStreamServer) {
	// If the following call panics, it indicates UnimplementedChangeStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChangeStream_ServiceDesc, srv)
}

func _ChangeStream_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangeStreamServer).StreamChanges(m, &grpc.GenericServerStream[StreamChangesRequest, Change]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChangeStream_StreamChangesServer = grpc.ServerStreamingServer[Change]

// ChangeStream_ServiceDesc is the grpc.ServiceDesc for ChangeStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdc.stream.v1.ChangeStream",
	HandlerType: (*ChangeStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChanges",
			Handler:       _ChangeStream_StreamChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cdc/stream/v1/changestream.proto",
}
